apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: it-asset-management
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: lassejonassen/inventoryservice:v1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
          env:
            - name: connectionstring
              valueFrom:
                secretKeyRef:
                  name: inventory-service-sql
                  key: connectionstring
            - name: jwtsecretkey
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwtsecretkey
