apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: it-asset-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: lassejonassen/orderservice:v1.0.0
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
