apiVersion: v1
kind: Service
metadata:
  name: authentication-svc
  namespace: it-asset-management
spec:
  type: ClusterIP
  selector:
    app: authentication
  ports:
    - port: 80
      targetPort: 80
