apiVersion: v1
kind: Service
metadata:
  name: client-app-loadbalancer
  namespace: it-asset-management
spec:
  type: LoadBalancer
  selector:
    app: client-app
  ports:
    - port: 80
      targetPort: 80
