apiVersion: v1
kind: Service
metadata:
  name: inventory-service-svc
  namespace: it-asset-management
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - name: inventory-service-svc
      protocol: TCP
      port: 80
      targetPort: 80
