apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
  namespace: it-asset-management
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: order-service-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
