apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  namespace: it-asset-management
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: user-service-svc
      protocol: TCP
      port: 80
      targetPort: 80
